# Generated by Django 4.1.5 on 2023-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('meta_description', models.CharField(max_length=155)),
                ('meta_tags', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('icon', models.ImageField(upload_to='serv_icon/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
