# Generated by Django 4.1.5 on 2023-02-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsubs',
            old_name='email',
            new_name='n_email',
        ),
    ]
